server:
  port: 8086

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:mysql://localhost:3306/buildflow_finance_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root # Replace with env variable in prod
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: finance-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.buildflow.project.dto.response.ProjectResponse:com.buildflow.finance.event.ProjectEvent,com.buildflow.project.entity.Project:com.buildflow.finance.event.ProjectEvent,com.buildflow.workforce.event.AttendanceEvent:com.buildflow.finance.event.AttendanceEvent,com.buildflow.workforce.event.FixedWorkAgreementEvent:com.buildflow.finance.event.FixedWorkAgreementEvent,com.buildflow.workforce.event.WageEvent:com.buildflow.finance.event.WageEvent,com.buildflow.inventory.entity.InventoryTransaction:com.buildflow.finance.event.InventoryTransactionEvent,com.buildflow.equipment.dto.event.EquipmentUsageEvent:com.buildflow.finance.event.EquipmentUsageEvent"

logging:
  level:
    com.buildflow.finance: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
